# initialization
units metal
dimension 3
atom_style atomic
boundary p p f

# lattice constant of Al
# physical distance between unit cells in a crystal lattice which definces the size of unit cell
variable lattice_size equal 4.05

# size of the simulation box
# side length: x_i = dx_i * box_size
# note: should be a multiple of 6
variable box_size equal 24

# lattice spacing (from logs)
variable dx equal 5.7275649
variable dy equal 6.6136223
variable dz equal 7.0148058
