# this file contains common stuff for all the other files:
# variables, system definition, potential settings

# --- variables --- #

variable desired_temp equal 300.0  # desired temperature, [K]

variable sigma equal 150.0  # applied stress, [bar] = [10^5 Pa]

variable layer_thresh equal 4.0  # height of upper and lower layers, [Ang]

# lattice constant of Al
variable a equal 4.05

# potentials
variable potential_al string potentials/NiAl_Mishin_2004.eam.alloy

# burgers vector
variable b equal $a/sqrt(2)

# steps amounts for runs
variable equilibration_run_steps equal 100
variable shear_run_steps         equal 10000

# 1 eV = 1.602176634e-19, but we use some other non-standard stuff, so we use it like this
# [bar*Ang*Ang] = [10^5 10^10 10^10] = [10^25]
# force [eV/Ang] = (stress [bar] * S [Ang^2]) / (N * eV_to_J)
variable eV_to_J equal 1602176.634

# --- system definition --- #

units      metal
dimension  3
atom_style atomic
boundary   p s p

# --- eam/alloy potential --- #

neighbor     2.0 bin
neigh_modify delay 5

# --- create directories if they don't exist --- #

shell mkdir logs/equilibrations
shell mkdir logs/shears

shell mkdir dumps/equilibrations
shell mkdir dumps/shears

shell mkdir restarts/equilibrations
