# common.ini
#
# common stuff for all the other files:
# variables and basic system definition

# ---           --- #
# --- variables --- #
# ---           --- #

# Al melting point: 933.47 K
# Mg melting point: 923.00 K

# desired temperature, [K]
variable desired_temp index 300.0

# applied stress for "in.shear-soft" script, [bar] = 10^5 [Pa]
variable shear_sigma equal 150.0

# top layer velocity for "in.shear-hard" script, [Ang/ps] = 100 [m/s]
variable shear_velocity equal 1e-4

# height of upper and lower layers, [Ang]
variable layer_thresh equal 2.0

# lattice constant of Al
variable a equal 4.05

# burgers vector (FCC)
variable b equal $a/sqrt(2)

# atomic masses, [g/mol]
variable al_mass equal 26.9815
variable mg_mass equal 24.3050

# fractions
variable mg_frac  index 0.05  # fraction of Mg atoms in the system (to replace Al atoms)
variable vac_frac index 0.001 # fraction of vacancies (after replacing Al with Mg)

# potentials
variable potential_al   string "potentials/NiAl_Mishin_2004.eam.alloy"
variable potential_almg string "potentials/Al-Mg.eam.fs"

# timesteps for runs, [ps] = 1e-12 [sec]
variable eq_run_timestep    equal 0.001 # 1e-3 * 1e-12 = 1e-15 [sec]
variable shear_run_timestep equal 0.002 # 2e-3 * 1e-12 = 2e-15 [sec]

# steps amounts for runs
variable eq_run_steps    index 3e4
variable seg_run_steps   index 5e5
variable shear_run_steps equal 5e6

# timestep frequency for dumps
variable eq_dump_freq    equal 500
variable shear_dump_freq equal 100

# 1 eV = 1.602176634e-19 J, but we use some other non-standard stuff, so we use it like this:
# [bar*Ang*Ang] = [10^5 10^10 10^10] = [10^25] => 1 eV = 1.6...e(-19+25) = 1.6...e6 = 1602176.634
variable eV_to_J equal 1602176.634

# force [eV/Ang] = (stress [bar] * S [Ang^2]) / (N * eV_to_J)

# ---                         --- #
# --- basic system definition --- #
# ---                         --- #

units      metal
dimension  3
atom_style atomic
boundary   p s p

# ---                                        --- #
# --- create directories if they don't exist --- #
# ---                                        --- #

shell mkdir logs/equilibrations
shell mkdir logs/shears

shell mkdir dumps/equilibrations
shell mkdir dumps/shears

shell mkdir restarts/equilibrations
