# common.ini
#
# common stuff for all the other files:
# variables, system definition, potential settings

# ---           --- #
# --- variables --- #
# ---           --- #

# desired temperature, [K]
variable desired_temp equal 300.0

# applied stress for "in.shear-soft" script, [bar] = 10^5 [Pa]
variable shear_sigma equal 150.0

# top layer velocity for "in.shear-hard" script, [Ang/ps] = 100 [m/s]
variable shear_velocity equal 0.01

# height of upper and lower layers, [Ang]
variable layer_thresh equal 2.0

# lattice constant of Al
variable a equal 4.05

# burgers vector (FCC)
variable b equal $a/sqrt(2)

# potentials
variable potential_al string "potentials/NiAl_Mishin_2004.eam.alloy"

# timesteps for runs
variable equilibration_run_timestep equal 0.001 # 1e-3 * 1e-12 = 1e-15 [sec]
variable shear_run_timestep         equal 0.002 # 2e-3 * 1e-12 = 2e-15 [sec]

# steps amounts for runs
variable equilibration_run_steps equal 10000 # total_time = 1e4 * 1e-15 = 1e-11 [sec]
variable shear_run_steps         equal 100000 # total_time = 1e5 * 2e-15 = 2e-10 [sec]

# timestep frequency for dumps
variable equilibration_dump_freq equal 100
variable shear_dump_freq         equal 100

# 1 eV = 1.602176634e-19 J, but we use some other non-standard stuff, so we use it like this:
# [bar*Ang*Ang] = [10^5 10^10 10^10] = [10^25] => 1 eV = 1.6...e(-19+25) = 1.6...e6 = 1602176.634
variable eV_to_J equal 1602176.634

# force [eV/Ang] = (stress [bar] * S [Ang^2]) / (N * eV_to_J)

# ---                   --- #
# --- system definition --- #
# ---                   --- #

units      metal
dimension  3
atom_style atomic
boundary   p s p

# ---                     --- #
# --- eam/alloy potential --- #
# ---                     --- #

neighbor     2.0 bin
neigh_modify delay 5

# ---                                        --- #
# --- create directories if they don't exist --- #
# ---                                        --- #

shell mkdir logs/equilibrations
shell mkdir logs/shears

shell mkdir dumps/equilibrations
shell mkdir dumps/shears

shell mkdir restarts/equilibrations
